//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpStozohilovEgor.МодельБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public int Стоимость { get; set; }
        public int Размер_максимально_возможной_скидки { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public int Категория_товара { get; set; }
        public float Действующая_скидка { get; set; }
        public int Количество_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
