//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpStozohilovEgor.МодельБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string Фамилия { get; set; }
        public string Имя_Отчество { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Роль { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
